Fix installer script for magisk compatibility
Signed-off-by: Yash D. Saraf <yashdsaraf@gmail.com>

diff --git a/bbx/META-INF/com/google/android/update-binary b/bbx/META-INF/com/google/android/update-binary
--- a/bbx/META-INF/com/google/android/update-binary
+++ b/bbx/META-INF/com/google/android/update-binary
@@ -20,19 +20,21 @@ ui_print() {
 
 error() {
     local ERRSTAT=$?
-    if [ $ERRSTAT -ne 0 ]
-        then
-        ui_print "  "
-        ui_print " ***Abort!!*** "
-        ui_print "Cause: $1"
-        [ ! -z $LOGFILE ] && ui_print "Check $LOGFILE for errors"
-        if [ $INSTALLDIR != "none" -a -d $INSTALLDIR/tmp.bbxyds ]
-            then rm -rf $INSTALLDIR/tmp.bbxyds
-        fi
-        [ "$_mounted" == "no" ] && umount /system
-        exit "$ERRSTAT"
-    else sleep 0.5
+    if [ $ERRSTAT -eq 0 ]
+        then sleep 0.5
+        return
     fi
+    ui_print "  "
+    ui_print " ***Abort!!*** "
+    ui_print "Cause: $1"
+    [ ! -z $LOGFILE ] && ui_print "Check $LOGFILE for errors"
+    if [ $INSTALLDIR != "none" -a -d $INSTALLDIR/tmp.bbxyds ]
+        then rm -rf $INSTALLDIR/tmp.bbxyds
+    fi
+    if [ "$_mounted" == "no" ]
+        then umount /system
+    fi
+    exit "$ERRSTAT"
 }
 
 is_mounted() {
@@ -86,8 +88,7 @@ set_permissions() {
 }
 
 #embedded mode support
-readlink /proc/$$/fd/$OPFD 2>/dev/null | grep /tmp >/dev/null
-if [ "$?" -eq "0" ]
+if readlink /proc/$$/fd/$OPFD 2>/dev/null | grep /tmp >/dev/null
     then
     OPFD=0
     for FD in `ls /proc/$$/fd`
@@ -188,45 +189,47 @@ for i in /sdcard /data /cache
 do
     if [ -f $i/bbx.conf ]
         then
-        ui_print "Found $i/bbx.conf --"
-        for line in `cat $i/bbx.conf`
-        do
-            option=${line%=*}
-            value=${line#*=}
-            case $option in
-                selinux)
-                    case $value in
-                        0) SELSTAT="DISABLED (user override)"
-                        ;;
-                        1) SELSTAT="ENABLED (user override)"
-                        ;;
-                        *) ui_print "Invalid option set for 'selinux' => $value (should be 0 or 1)"
-                        ;;
-                    esac
-                ;;
-                noclean)
-                    NOCLEAN=1
-                ;;
-                installdir)
-                    if ! [ -z $value ]
-                        then
-                        if ! [ -e $value ]
-                            then mkdir $value
-                            error "Error while creating $value"
-                            set_permissions $value 0755 0 0 u:object_r:system_file:s0
-                            INSTALLDIR=$value
-                        elif ! [ -d $value -a -w $value ]
-                            then ui_print "Directory not accessible => $value"
-                        else INSTALLDIR=$value
-                        fi
-                    else ui_print "Installation directory cannot be empty"
+        continue
+    fi
+    ui_print "Found $i/bbx.conf --"
+    for line in `cat $i/bbx.conf`
+    do
+        option=${line%=*}
+        value=${line#*=}
+        case $option in
+            selinux)
+                case $value in
+                    0) SELSTAT="DISABLED (user override)"
+                    ;;
+                    1) SELSTAT="ENABLED (user override)"
+                    ;;
+                    *) ui_print "Invalid option set for 'selinux' => $value (should be 0 or 1)"
+                    ;;
+                esac
+            ;;
+            noclean)
+                NOCLEAN=1
+            ;;
+            installdir)
+                if ! [ -z $value ]
+                    then
+                    if ! [ -e $value ]
+                        then mkdir $value
+                        error "Error while creating $value"
+                        set_permissions $value 0755 0 0 u:object_r:system_file:s0
+                        INSTALLDIR=$value
+                    elif ! [ -d $value -a -w $value ]
+                        then ui_print "Directory not accessible => $value"
+                    else INSTALLDIR=$value
                     fi
-                ;;
-                *) ui_print "Invalid entry in config => $option"
-                ;;
-            esac
-        done
-        break
+                else ui_print "Installation directory cannot be empty"
+                fi
+            ;;
+            *) ui_print "Invalid entry in config => $option"
+            ;;
+        esac
+    done
+    break
     fi
 done
 unset i
@@ -247,11 +250,16 @@ MAGISK=$(
     ls /data/magisk.img || ls /cache/magisk.img
 ) 2>/dev/null
 
-if ! [ -z "$SUIMG" -a -z "$MAGISK" ]
-    then
-    ui_print "Systemless root detected --"
-    [ -z "$SUIMG" ] || SULOOPDEV=$(mount_systemless $SUIMG "/su")
-    [ -z "$MAGISK" ] || MAGISKLOOPDEV=$(mount_systemless $MAGISK "/magisk")
+if [ ! -z "$SUIMG" ]
+    then SULOOPDEV=$(mount_systemless $SUIMG "/su")
+fi
+
+if [ ! -z "$MAGISK" ]
+    then MAGISKLOOPDEV=$(mount_systemless $MAGISK "/magisk")
+fi
+
+if ! [ -z "$SULOOPDEV" -a -z "$MAGISKLOOPDEV" ]
+    then ui_print "Systemless root detected --"
 fi
 
 POSSIBLE_INSTALLDIRS="/su/xbin /magisk/phh/bin /system/xbin /system/vendor/bin /vendor/bin"
@@ -282,8 +290,9 @@ if [ -z $NOCLEAN ]
     POSSIBLE_CLEANDIRS="/system/xbin /system/bin /su/xbin /su/bin /magisk/phh/bin /vendor/bin /system/vendor/bin $USER_INSTALLDIR"
     for dir in $POSSIBLE_CLEANDIRS
     do
-        if [ -e $dir/busybox ]
-            then
+        if [ ! -e $dir/busybox ]
+            then continue
+        fi
             ui_print "Found in $dir --"
             cd $dir
             count=0
@@ -336,7 +345,11 @@ do
     # Only install applets which are not present in the system
     # Fixes the error of busybox applets being called instead of system's default applets
     # since magisk installs bins to /sbin which precedes /system
-    if [ "$INSTALLDIR" == "/magisk/phh/bin" ] && [ -e /system/bin/$i -o -e /system/xbin/$i ]
+    if [ "$INSTALLDIR" == "/magisk/phh/bin" ] &&
+        for dir in $POSSIBLE_CLEANDIRS
+        do
+            [ -e $dir/$i ] && break
+        done
         then continue
     fi
     ./busybox ln -s busybox $i 2>/dev/null
